# Site settings
DefaultContentLanguage = "de"
defaultContentLanguageInSubdir = "true"
title = "matthias schnetzer"
baseURL = "https://mschnetzer.github.io/"
theme = "hugo-agency-theme"
canonifyURLs = "true"

[languages]
[languages.de]
  languageName = "Deutsch"
  weight = 1
[languages.en]
  languageName = "English"
  weight = 2

[params]
  name = "Matthias Schnetzer"
  custom_css = []
  custom_js  = []
  disableFonts = false

#########################
# 404 error customization
  [languages.de.error404]
    heading = "Seite konnte nicht gefunden werden!"
    text = "Bitte zurück [zur Startseite](/)"

  [languages.en.error404]
    heading = "Page not found!"
    text = "Back [to the Homepage](/)"

############
# Navigation
  [languages.de.navigation]
    brand = "matthias schnetzer"
    posts = "Blog"
    portfolio = "Publikationen"
    about = "CV"
    services = "Lehre"

  [languages.en.navigation]
    brand = "matthias schnetzer"
    posts = "Blog"
    portfolio = "Publications"
    about = "CV"
    services = "Teaching"

##############
# Header section
  [languages.de.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in the 'static/img' folder.
    # title = "political &middot; economist"
    # subtitle = "posts & papers"
    buttonText = "Weiterlesen"

  [languages.en.hero]
    # subtitle = "posts & papers"
    buttonText = "Read more"

##################
# Lehre section
  [languages.de.services]
    enable = true
    title = "Lehre"

    [[languages.de.services.row]]

      [[languages.de.services.row.list]]
        icon = "fa-balance-scale"
        title = "Ökonomie der Verteilung"
        description = "Vertiefungsfach im Masterstudium Volkswirtschaftslehre an der WU Wien."
        #url = "http://vvz.wu.ac.at/cgi-bin/vvz.pl?C=L;I=5174;LV=3;L2=S;L3=S;S=17S;LANG=DE"

    [[languages.de.services.row.list]]
      icon = "fa-chart-bar"
      title = "Verteilung und Wachstum"
      description = "Lehrveranstaltung im Masterstudium Volkswirtschaftslehre (Applied track) der WU Wien."
      #url = "http://vvz.wu.ac.at/cgi-bin/vvz.pl?C=L;I=6113;LV=3;L2=S;L3=S;S=17S;LANG=DE"

    [[languages.de.services.row.list]]
      icon = "fa-comments"
      title = "Kontakt"
      description = "Sprechstunde nach Vereinbarung. Kontaktaufnahme [per Mail](mailto:matthias.schnetzer@akwien.at)."
      #url = "mailto:matthias.schnetzer@akwien.at"

  [languages.en.services]
    enable = true
    title = "Teaching"

    [[languages.en.services.row]]

      [[languages.en.services.row.list]]
        icon = "fa-balance-scale"
        title = "Economics of distribution"
        description = "Master's course at the Department of Economics, WU Vienna."

    [[languages.en.services.row.list]]
      icon = "fa-chart-bar"
      title = "Distribution and growth"
      description = "Master's course at the Department of Economics, WU Vienna."

    [[languages.en.services.row.list]]
      icon = "fa-comments"
      title = "Contact"
      description = "Please contact me via [my email address](mailto:matthias.schnetzer@akwien.at)."

###############
# Blogs section
  [languages.de.posts]
    enable = true
    title = "Neueste Blogbeiträge"
    morepost = "Weitere Beiträge"

  [languages.en.posts]
    enable = false
    title = "Latest blogposts"
    morepost = "More blogposts"

###################
# Publikationen section
  [languages.de.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory at the root of this Hugo site.
    title = "Ausgewählte Publikationen"
    # subtitle = "A selection of my work"

    [languages.de.portfolio.modal]
      togetherwith = "gemeinsam mit"
      downlad = "Link"
      category = "Kategorie"
      buttonText = "Publikation schließen"

  [languages.en.portfolio]
    enable=true
    title= "Selected publications"

    [languages.en.portfolio.modal]
      togetherwith = "co-authored by"
      downlad = "Download"
      category = "Category"
      buttonText = "Close publication"

###############
# CV section
  [languages.de.about]
    enable = true
    title = "Über mich"
    # subtitle = "Lorem ipsum dolor sit amet consectetur."
    endpointshow = true
    endpoint = "Hier<br>klicken<br>für CV"
    endpointlink = "/cv_schnetzer.pdf"

    [[languages.de.about.events]]
      img = "ak.jpg"
      date = "seit 2013"
      title = "Ökonom, Arbeiterkammer Wien"
      description = "Abteilung Wirtschaftswissenschaften und Statistik, Referent für Verteilungsfragen"

    [[languages.de.about.events]]
      img = "wu.png"
      date = "seit 2010"
      title = "Lektor, Wirtschaftsuniversität Wien"
      description = "Institut für Makroökonomie, Lehrveranstaltungen zu Wirtschaftspolitik und politischer Ökonomie"

    [[languages.de.about.events]]
      img = "bmask.jpg"
      date = "2015"
      title = "Anerkennungspreis, Sozialministerium"
      description = "Wissenschaftspreis des Bundesministeriums für Soziales, Arbeit und Konsumentenschutz für Jungakademiker, Würdigung der Dissertation"

    [[languages.de.about.events]]
      img = "matzner.jpg"
      date = "2016"
      title = "Egon-Matzner-Preis für Sozioökonomie"
      description = "Preis des Instituts für Finanzwissenschaft und Infrastrukturpolitik an der TU Wien für einen Beitrag zu Vermögenskonzentration und Machtgefälle"

  [[languages.de.about.events]]
      img = "rothschild.jpg"
      date = "2016"
      title = "Kurt-Rothschild-Preis für Wirtschaftspublizstik"
      description = "Preis des Renner-Instituts und des SPÖ-Parlamentsklubs für einen Beitrag zur Rolle von Erbschaften beim Vermögensaufbau"

  [[languages.de.about.events]]
      img = "iariw.jpg"
      date = "2018"
      title = "Nancy and Richard Ruggles Memorial Prize"
      description = "Vergeben durch die International Association for Research in Income and Wealth (IARIW)"

  [languages.en.about]
      enable = true
      title = "About me"
      # subtitle = "Lorem ipsum dolor sit amet consectetur."
      endpointshow = true
      endpoint = "Click<br>here<br>for CV"
      endpointlink = "/cv_schnetzer_en.pdf"

      [[languages.en.about.events]]
        img = "ak.jpg"
        date = "since 2013"
        title = "Economist, Austrian Federal Chamber of Labor"
        description = "Department of Economics and Statistics"

      [[languages.en.about.events]]
        img = "wu.png"
        date = "since 2010"
        title = "Lecturer, Vienna University of Economics and Business"
        description = "Department of Economics, Institute for Macroeconomics"

      [[languages.en.about.events]]
        img = "bmask.jpg"
        date = "2015"
        title = "Appreciation award, Austrian Ministry for Social Affairs"
        description = "Award for young scholars, Appreciation for the dissertation"

      [[languages.en.about.events]]
        img = "matzner.jpg"
        date = "2016"
        title = "Egon-Matzner-Award for Socio-Economics"
        description = "Awarded by the Centre of Public Finance and Infrastructure Policy at the TU Wien"

      [[languages.en.about.events]]
        img = "rothschild.jpg"
        date = "2016"
        title = "Kurt-Rothschild-Award"
        description = "Awarded by the Karl Renner Institute and the Austrian Socialdemocratic Party"

      [[languages.en.about.events]]
        img = "iariw.jpg"
        date = "2018"
        title = "Nancy and Richard Ruggles Memorial Prize"
        description = "Awarded by the International Association for Research in Income and Wealth (IARIW)"

################
# Footer section
  [languages.de.footer]
    enable = true
    copyright = "&nbsp;&middot; erstellt mit [Hugo](http://gohugo.io) &middot; Titelfoto von [Phirue](http://philippruemmele.com)"

  [languages.en.footer]
    enable = true
    copyright = "&nbsp;&middot; created with [Hugo](http://gohugo.io) &middot; Image by [Phirue](http://philippruemmele.com)"

    # [[params.footer.social]]
    #  icon = "fa-twitter"
    #  link = "http://www.twitter.com"

    # [[params.footer.social]]
    #  icon = "fa-facebook"
    #  link = "http://www.facebook.com"
